### ISSUE TITLE
Update to NES.css 1.0.0

### ISSUE THREAD

**Issue by guastallaigor** [jefer590/vuenes.css#2]
Hello! I was thinking of creating a project like this myself but I find yours so I'm going to help you if I can.

We've just released version 1.0.0 on NES.css, and launch a few others components/icons/classes, and almost every class is going to break because we added a `nes-` prefix to every component.

I've tried to fork and update your project, but I didn't manage to understand how are you serving your project or testing it? I mean, you have 100% unit testing and that's awesome, but I want to see then visually, because even if I update to 1.0.0 in my fork and not make any change, your unit tests is going to pass, so to me just unit testing without seeing anything is not 100% reliable.

If you can give me some instructions on how I can help you update your project, that would be great :+1:  . Giving you a heads up, I'm not very familiarized with jest unit testing but I give it my best :smile: 

Thank you.

**Comment by fernyettheplant** [comment]
hey there @guastallaigor 👋 now that you mentioned, I need to add storybook to this project, just to make sure of the visual part works 😬 I can work on that in a few.

In theory, in a clean installation with VueCLI 3, in the `{main|index}.js` if you do:
```js
import Vue from 'vue'
import VueNesCss from 'vuenes.css'

Vue.use(VueNesCss)
```

should be available globally and you can start testing/use the library. worth to mention, I need to make available each component to be used individually instead of register it globally. That's 🔜

**Comment by fernyettheplant** [comment]
Update: I've prepared the PR #4 which included the newest version of the CSS library 🙂

**Comment by guastallaigor** [comment]
That's awesome @jefer590 , thank you 😄.
 We are still working on some bugs before releasing v1.1.0, but with storybooks and so on I think I can help you with some PRs for when we released it. 👍

**Comment by fernyettheplant** [comment]
Closing this.

`2.0.0` has been published on `npmjs` 🎉
